#!/usr/bin/env perl
# morbo -v -w lk/lib/ -l http://*:83 ./lk/script/lk
use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('LK');
